### ISSUE TITLE
Configuration property 'kudu.client.defaultOperationTimeout' was not used   at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

### ISSUE THREAD

**Issue by lightsailpro** [MartinWeindel/presto-kudu#14]
After setting the following in kudu.property, the server will not start.  Did I miss anything? Thanks

#######################
#######################
## Disable Kudu client's collection of statistics.
#kudu.client.disableStatistics=false
## Default timeout used for user operations
kudu.client.defaultOperationTimeout=60s
## Default timeout to use when waiting on data from a socket
kudu.client.defaultSocketReadTimeout=60s

Here are the errors:
2019-02-04T15:56:45.922-0500	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Configuration property 'kudu.client.defaultOperationTimeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2) Configuration property 'kudu.client.defaultSocketReadTimeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'kudu.client.defaultOperationTimeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2) Configuration property 'kudu.client.defaultSocketReadTimeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
	at com.facebook.presto.kudu.KuduConnectorFactory.create(KuduConnectorFactory.java:58)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:319)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:121)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:68)

**Comment by lightsailpro** [comment]
The following format works:
kudu.client.default-socket-read-timeout = 300s

**Comment by MartinWeindel** [comment]
You seem to use the integrated Kudu connector in the Presto distribution.
For the correct configuration values please see Presto documentation at
https://prestodb.github.io/docs/current/connector/kudu.html#configuration

**Comment by MartinWeindel** [comment]
resolved
